[package]
name = "text_signature"
version = "0.1.0"
edition = "2021"
description = "text signature"

[lib]
path = "lib.rs"

[dependencies]
polyglot_rs = "0.6.0"
scale_signature = "0.2.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1